/* β版の保存・育成ロジック。時刻を受け取り、Nodeでも再現可能にする。 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.LittleCompanionLife = factory();
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  const clamp = value => Math.max(0, Math.min(100, Math.round(Number(value) || 0)));
  const today = now => { const date = now instanceof Date ? now : new Date(now || Date.now()); const pad = value => String(value).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`; };
  const safeText = value => String(value || '').replace(/[<>]/g, '').replace(/[\u0000-\u001f]/g, '').trim().slice(0, 20);
  const safeTimestamp = value => String(value || '').replace(/[<>]/g, '').replace(/[\u0000-\u001f]/g, '').trim().slice(0, 30);
  const privateLike = value => /(?:\d{2,4}[-\s]?\d{2,4}[-\s]?\d{3,4}|[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}|住所|電話|学校|メール|顔写真|(?:東京都|北海道|(?:大阪|京都)府|.{2,3}県).{1,20}(?:市|区|町|村))/i.test(value);
  function createDefaultState(now) {
    const stamp = safeTimestamp(new Date(now || Date.now()).toISOString());
    const bondStory = defaultWordStory('p-default');
    return {
      version:8, petName:'ぽこ', childName:'', soundMode:'pet', voiceMemoryEnabled:false, echoModeEnabled:true,
      voiceTuning:{pitchRate:1.42,speedRate:1,doubleMix:.18,brightness:60,timingMode:'preserve'}, echoVoiceOverrides:{}, speechInputEnabled:true, cameraEnabled:false,
      bond:10, energy:80, mood:70, curiosity:50, likes:[], dislikes:[], careCount:{tap:0,stroke:0,hold:0,play:0,sleep:0,talk:0},
      traits:{playful:50,calm:50,talkative:50}, urge:'curious', attention:50, surpriseSeed:17, socialMood:'curious',
      routine:{morning:{},day:{},evening:{},night:{}}, recentActionKinds:[], callbackQueue:[],
      profiles:[{id:'p-default',name:'いつものひと',childName:'',likes:[],dislikes:[],recentMoods:[],visitDates:[],createdAt:stamp,lastSeenAt:'',interactionCount:0,activePetId:'pet-1',activePetTurnCount:0,switchAfterTurn:2}],
      activeProfileId:'p-default', weekProgress:{visitDates:[],dayIndex:1,dailyBeat:'greeting',dayHistory:{},lastCallbackAt:'',completedAt:''},
      factMemories:[], playMemories:[], safetyPausedAt:'',
      daily:{date:today(now),talk:0,touch:0,play:0,seenReplyIds:[],echoInviteCount:0,echoSessionCount:0,echoRoundCount:0,lastEchoInviteAt:''},
      themeDates:{}, recentMoods:[], questionAnswers:0, learnedWords:[], bondStory,
      wordMemoryV2:{stories:[bondStory],requestDate:'',requestProfileId:'',deletionLedger:[]},
      pets:defaultPets('ぽこ'), profilePetStates:[defaultProfilePetState('p-default','pet-1'),defaultProfilePetState('p-default','pet-2')],
      pairRelations:[defaultPairRelation('p-default')], ownPreference:'round', moments:[], bondStage:0,lastSeenAt:'',lastReplies:[],
      trouble:{active:null,daily:{date:today(now),count:0,kinds:[]},helpLog:[],helpTotal:0,enabled:true},
      ritual:defaultRitual(today(now))
    };
  }
  function defaultRitual(date) {
    return { date, morning:{'pet-1':{woke:false,at:'',tries:0,autoAt:''},'pet-2':{woke:false,at:'',tries:0,autoAt:''}}, meal:{done:false,at:''}, night:{'pet-1':{tucked:false,at:''},'pet-2':{tucked:false,at:''}}, yesterday:null, log:[], streak:0, yawns:{'pet-1':'','pet-2':''}, enabled:true };
  }
  function normalizeRitual(raw, now) {
    const ritual = defaultRitual(/^\d{4}-\d{2}-\d{2}$/.test(String(raw && raw.date || '')) ? String(raw.date) : today(now));
    ['pet-1','pet-2'].forEach(id => {
      const morning = raw && raw.morning && typeof raw.morning === 'object' && raw.morning[id] && typeof raw.morning[id] === 'object' ? raw.morning[id] : {};
      ritual.morning[id] = { woke:morning.woke === true, at:safeTimestamp(morning.at), tries:Math.max(0, Math.min(99, Math.floor(Number(morning.tries) || 0))), autoAt:safeTimestamp(morning.autoAt) };
      const night = raw && raw.night && typeof raw.night === 'object' && raw.night[id] && typeof raw.night[id] === 'object' ? raw.night[id] : {};
      ritual.night[id] = { tucked:night.tucked === true, at:safeTimestamp(night.at) };
      ritual.yawns[id] = safeTimestamp(raw && raw.yawns && typeof raw.yawns === 'object' && raw.yawns[id]);
    });
    const meal = raw && raw.meal && typeof raw.meal === 'object' ? raw.meal : {};
    ritual.meal = { done:meal.done === true, at:safeTimestamp(meal.at) };
    const yesterday = raw && raw.yesterday && typeof raw.yesterday === 'object' ? raw.yesterday : null;
    if (yesterday && /^\d{4}-\d{2}-\d{2}$/.test(String(yesterday.date || ''))) {
      const morning = {}; const night = {};
      ['pet-1','pet-2'].forEach(id => { morning[id] = yesterday.morning && typeof yesterday.morning === 'object' && yesterday.morning[id] === true; night[id] = yesterday.night && typeof yesterday.night === 'object' && yesterday.night[id] === true; });
      ritual.yesterday = { date:String(yesterday.date), morning, meal:yesterday.meal === true, night, all:yesterday.all === true };
    }
    ritual.log = Array.isArray(raw && raw.log) ? raw.log.map(item => ({ date:safeText(item && item.date).slice(0, 10), woke:Math.max(0, Math.min(2, Math.floor(Number(item && item.woke) || 0))), meal:item && item.meal === true, tucked:Math.max(0, Math.min(2, Math.floor(Number(item && item.tucked) || 0))), all:item && item.all === true })).filter(item => /^\d{4}-\d{2}-\d{2}$/.test(item.date)).slice(-30) : [];
    ritual.streak = Math.max(0, Math.floor(Number(raw && raw.streak) || 0));
    ritual.enabled = !(raw && raw.enabled === false);
    return ritual;
  }
  function listSafe(values) { return Array.isArray(values) ? values.map(safeText).filter(value => value && !privateLike(value)).slice(-5) : []; }
  function defaultWordStory(profileId = 'p-default') { return { profileId, chapter:'find', beat:'idle', pendingWordId:'', lastBeatAt:'', unrelatedActions:0, completedAt:'', lastCompletedAt:'', recallReadyAt:'', eventDates:{}, preferenceShown:false }; }
  function defaultPets(firstName = 'ぽこ') { return [
    {id:'pet-1',name:safeText(firstName).slice(0,12)||'ぽこ',baseTemperament:{curious:70,cautious:30,calm:45}},
    {id:'pet-2',name:'ふわ',baseTemperament:{curious:35,cautious:70,calm:70}}
  ]; }
  function defaultProfilePetState(profileId, petId, legacy = null) { const source = legacy && typeof legacy === 'object' ? legacy : {}; const traits = source.traits && typeof source.traits === 'object' ? source.traits : {}; return { profileId, petId, bond:clamp(source.bond === undefined ? 10 : source.bond), mood:clamp(source.mood === undefined ? 70 : source.mood), energy:clamp(source.energy === undefined ? 80 : source.energy), traits:{playful:clamp(traits.playful === undefined ? 50 : traits.playful),calm:clamp(traits.calm === undefined ? 50 : traits.calm),talkative:clamp(traits.talkative === undefined ? 50 : traits.talkative)},lastExpression:['normal','happy','sad','sleepy','thinking','talking','watching','ear-react','body-react'].includes(source.lastExpression)?source.lastExpression:'normal'}; }
  function defaultPairRelation(profileId) { return {profileId,petIds:['pet-1','pet-2'],phase:'solo',visitCount:0,affinity:0,friendshipStage:'not-met',soloCareCount:0,soloCareKinds:[],sharedWords:[],sharedToys:[],sharedEvents:[],recentSceneIds:[],lastEventAt:'',cohabitedAt:''}; }
  function normalizeActivePetIds(data) {
    if (!data || !Array.isArray(data.profiles)) return data;
    data.profiles.forEach(profile => {
      const relation = (data.pairRelations || []).find(item => item && item.profileId === profile.id);
      profile.activePetId = relation && ['visiting','cohabiting'].includes(relation.phase) && profile.activePetId === 'pet-2' ? 'pet-2' : 'pet-1';
      profile.activePetTurnCount = Math.max(0, Math.min(4, Math.floor(Number(profile.activePetTurnCount) || 0)));
      profile.switchAfterTurn = Math.max(2, Math.min(4, Math.floor(Number(profile.switchAfterTurn) || 2)));
    });
    return data;
  }
  function limitedWords(values) { const counts = Object.create(null); return values.filter(item => { const id = item.profileId || 'p-default'; counts[id] = (counts[id] || 0) + 1; return counts[id] <= 20; }); }
  function normalizeWordStory(value, profileId) { const raw = value && typeof value === 'object' ? value : {}; return {profileId,chapter:safeText(raw.chapter).slice(0,20)||'find',beat:safeText(raw.beat).slice(0,20)||'idle',pendingWordId:safeText(raw.pendingWordId).slice(0,40),lastBeatAt:safeTimestamp(raw.lastBeatAt),unrelatedActions:Math.max(0,Math.min(2,Number(raw.unrelatedActions)||0)),completedAt:safeTimestamp(raw.completedAt),lastCompletedAt:safeTimestamp(raw.lastCompletedAt||raw.completedAt),recallReadyAt:safeTimestamp(raw.recallReadyAt),eventDates:raw.eventDates&&typeof raw.eventDates==='object'?Object.fromEntries(Object.entries(raw.eventDates).map(([key,val])=>[safeText(key).slice(0,30),safeText(val).slice(0,12)]).filter(([,val])=>val)):{},preferenceShown:Boolean(raw.preferenceShown)}; }
  function normalizeV6Structures(data, old, now) {
    const oldWordMemory = old.wordMemoryV2 && typeof old.wordMemoryV2 === 'object' ? old.wordMemoryV2 : {};
    const sourceStories = Array.isArray(oldWordMemory.stories) ? oldWordMemory.stories : [];
    data.wordMemoryV2 = {
      stories:data.profiles.map(profile => {
        const source = sourceStories.find(item => item && item.profileId === profile.id) || (profile.id === data.activeProfileId ? old.bondStory : null);
        return normalizeWordStory(source, profile.id);
      }),
      requestDate:/^\d{4}-\d{2}-\d{2}$/.test(String(oldWordMemory.requestDate || '')) ? String(oldWordMemory.requestDate) : '',
      requestProfileId:data.profiles.some(profile => profile.id === oldWordMemory.requestProfileId) ? oldWordMemory.requestProfileId : '',
      deletionLedger:Array.isArray(oldWordMemory.deletionLedger) ? oldWordMemory.deletionLedger.map((item,index) => ({id:safeText(item&&item.id).slice(0,40)||`delete-${index}`,kind:item&&item.kind==='profile'?'profile':'word',profileId:safeText(item&&item.profileId).slice(0,30)||'p-default',wordId:safeText(item&&item.wordId).slice(0,40),createdAt:safeTimestamp(item&&item.createdAt)})).filter(item => item.profileId && (item.kind === 'profile' || item.wordId)).slice(-40) : []
    };
    data.bondStory = data.wordMemoryV2.stories.find(item => item.profileId === data.activeProfileId) || data.wordMemoryV2.stories[0] || defaultWordStory(data.activeProfileId);

    const petDefaults = defaultPets(data.petName);
    const oldPets = Array.isArray(old.pets) ? old.pets : [];
    data.pets = petDefaults.map(fallback => { const source = oldPets.find(item => item && item.id === fallback.id) || {}; const temperament = source.baseTemperament && typeof source.baseTemperament === 'object' ? source.baseTemperament : fallback.baseTemperament; return {id:fallback.id,name:safeText(source.name).slice(0,12)||fallback.name,baseTemperament:{curious:clamp(temperament.curious),cautious:clamp(temperament.cautious),calm:clamp(temperament.calm)}}; });
    const oldPetStates = Array.isArray(old.profilePetStates) ? old.profilePetStates : [];
    const legacy = {bond:data.bond,mood:data.mood,energy:data.energy,traits:data.traits,lastExpression:'normal'};
    data.profilePetStates = data.profiles.flatMap(profile => data.pets.map(petItem => {
      const existing = oldPetStates.find(item => item && item.profileId === profile.id && item.petId === petItem.id);
      return defaultProfilePetState(profile.id, petItem.id, existing || (petItem.id === 'pet-1' ? legacy : null));
    }));
    const oldRelations = Array.isArray(old.pairRelations) ? old.pairRelations : [];
    data.pairRelations = data.profiles.map(profile => {
      const source = oldRelations.find(item => item && item.profileId === profile.id) || {};
      const relation = defaultPairRelation(profile.id);
      relation.phase = ['solo','visiting','cohabiting'].includes(source.phase) ? source.phase : 'solo';
      relation.visitCount = Math.max(0,Math.min(3,Math.floor(Number(source.visitCount)||0)));
      relation.affinity = clamp(source.affinity);
      relation.friendshipStage = ['not-met','visiting','familiar','together'].includes(source.friendshipStage) ? source.friendshipStage : relation.visitCount >= 3 ? 'together' : relation.visitCount ? 'visiting' : 'not-met';
      relation.soloCareCount = Math.max(0,Number(source.soloCareCount)||0);
      relation.soloCareKinds = Array.isArray(source.soloCareKinds) ? [...new Set(source.soloCareKinds.map(safeText).filter(kind => ['tap','stroke','hold','play','sleep'].includes(kind)))].slice(0,5) : [];
      relation.sharedWords = Array.isArray(source.sharedWords) ? source.sharedWords.map(item => ({profileId:profile.id,wordId:safeText(item&&item.wordId).slice(0,40),taughtByPetId:item&&item.taughtByPetId==='pet-2'?'pet-2':'pet-1',sharedWithPetId:item&&item.sharedWithPetId==='pet-1'?'pet-1':'pet-2',sharedAt:safeTimestamp(item&&item.sharedAt),lastUsedAt:safeTimestamp(item&&item.lastUsedAt)})).filter(item => item.wordId && data.learnedWords.some(word => word.profileId === profile.id && word.id === item.wordId)).slice(-20) : [];
      relation.sharedToys = Array.isArray(source.sharedToys) ? source.sharedToys.map(item => ({toyId:safeText(item&&item.toyId).slice(0,30),petIds:['pet-1','pet-2'],firstAt:safeTimestamp(item&&item.firstAt),lastAt:safeTimestamp(item&&item.lastAt),playCount:Math.max(0,Number(item&&item.playCount)||0)})).filter(item => item.toyId).slice(-20) : [];
      relation.sharedEvents = Array.isArray(source.sharedEvents) ? source.sharedEvents.map(item => ({id:safeText(item&&item.id).slice(0,50),sceneId:safeText(item&&item.sceneId).slice(0,40),petIds:['pet-1','pet-2'],wordId:safeText(item&&item.wordId).slice(0,40),toyId:safeText(item&&item.toyId).slice(0,30),at:safeTimestamp(item&&item.at)})).filter(item => item.id && item.sceneId && (!item.wordId || data.learnedWords.some(word => word.profileId === profile.id && word.id === item.wordId))).slice(-60) : [];
      relation.recentSceneIds = Array.isArray(source.recentSceneIds) ? [...new Set(source.recentSceneIds.map(value => safeText(value).slice(0,40)).filter(Boolean))].slice(-12) : [];
      relation.lastEventAt = safeTimestamp(source.lastEventAt); relation.cohabitedAt = safeTimestamp(source.cohabitedAt);
      if (relation.visitCount >= 3) { relation.phase = 'cohabiting'; relation.friendshipStage = 'together'; }
      return relation;
    });
  }
  function migrateState(raw, now = new Date()) {
    let old = raw;
    if (typeof raw === 'string') { try { old = JSON.parse(raw); } catch (_) { old = null; } }
    const data = createDefaultState(now); if (!old || typeof old !== 'object') return data;
    Object.assign(data, old);
    data.version = 6;
    data.petName = safeText(old.petName).slice(0, 12) || 'ぽこ'; data.childName = safeText(old.childName).slice(0, 12);
    if (privateLike(data.petName) || /死にたい|自殺|けが|怪我|薬|裸|性的|エッチ/.test(data.petName)) data.petName = 'ぽこ'; if (privateLike(data.childName) || /死にたい|自殺|けが|怪我|薬|裸|性的|エッチ/.test(data.childName)) data.childName = '';
    data.soundMode = old.soundMode === 'pet' || old.soundMode === 'text' || old.soundMode === 'auto' ? old.soundMode : old.soundEnabled === false ? 'text' : 'auto';
    data.voiceMemoryEnabled = old.voiceMemoryEnabled === true;
    data.echoModeEnabled = Number(old.version) >= 8 ? old.echoModeEnabled === true : true; const tune = old.voiceTuning && typeof old.voiceTuning === 'object' ? old.voiceTuning : {}; const tuneNumber = (key, fallback, min, max) => typeof tune[key] === 'number' && Number.isFinite(tune[key]) ? Math.max(min, Math.min(max, tune[key])) : fallback; data.voiceTuning = { pitchRate:tuneNumber('pitchRate',1.42,1.2,3.5), speedRate:tuneNumber('speedRate',1,.7,1.4), doubleMix:tuneNumber('doubleMix',.18,.08,.36), brightness:Math.round(tuneNumber('brightness',60,0,100)), timingMode:tune.timingMode === 'fast' ? 'fast' : 'preserve' }; const rawOverrides = old.echoVoiceOverrides && typeof old.echoVoiceOverrides === 'object' ? old.echoVoiceOverrides : {}; data.echoVoiceOverrides = {}; ['pet-1','pet-2'].forEach(petId => { const item=rawOverrides[petId]; if (!item || typeof item !== 'object') return; const number=(key,min,max)=>Number.isFinite(Number(item[key])) ? Math.max(min,Math.min(max,Number(item[key]))) : null; const pitch=number('pitchRate',.55,3.5), speed=number('speedRate',.7,1.4), doubleMix=number('doubleMix',0,.36), brightness=number('brightness',0,100); if (pitch !== null && speed !== null && doubleMix !== null && brightness !== null) data.echoVoiceOverrides[petId]={pitchRate:pitch === 1 ? 1.2 : pitch,speedRate:speed,doubleMix,brightness:Math.round(brightness),timingMode:item.timingMode === 'fast' ? 'fast' : 'preserve'}; });
    data.bond = clamp(old.bond === undefined ? data.bond : old.bond); data.energy = clamp(old.energy === undefined ? data.energy : old.energy); data.mood = clamp(old.mood === undefined ? data.mood : old.mood); data.curiosity = clamp(old.curiosity === undefined ? 50 : old.curiosity);
    data.likes = listSafe(old.likes); data.dislikes = listSafe(old.dislikes);
    data.careCount = { ...data.careCount, ...(old.careCount || {}) }; data.traits = { ...data.traits, ...(old.traits || {}) };
    Object.keys(data.careCount).forEach(key => { data.careCount[key] = Math.max(0, Number(data.careCount[key]) || 0); }); Object.keys(data.traits).forEach(key => { data.traits[key] = clamp(data.traits[key]); });
    const oldDaily = old.daily && old.daily.date === today(now) ? old.daily : { date:today(now), talk:0, touch:0, play:0, seenReplyIds:[], echoInviteCount:0, echoSessionCount:0, echoRoundCount:0, lastEchoInviteAt:'' };
    data.daily = { date:today(now), talk:Number(oldDaily.talk) || 0, touch:Number(oldDaily.touch) || 0, play:Number(oldDaily.play) || 0, seenReplyIds:Array.isArray(oldDaily.seenReplyIds) ? oldDaily.seenReplyIds.slice(-50) : [], echoInviteCount:Math.max(0, Math.min(5, Math.floor(Number(oldDaily.echoInviteCount) || 0))), echoSessionCount:Math.max(0, Math.floor(Number(oldDaily.echoSessionCount) || 0)), echoRoundCount:Math.max(0, Math.floor(Number(oldDaily.echoRoundCount) || 0)), lastEchoInviteAt:safeTimestamp(oldDaily.lastEchoInviteAt) };
    data.themeDates = old.themeDates && typeof old.themeDates === 'object' ? Object.fromEntries(Object.entries(old.themeDates).map(([key,value]) => [safeText(key).slice(0,20), safeText(value).slice(0,10)]).filter(([,value]) => value)) : {};
    data.recentMoods = Array.isArray(old.recentMoods) ? old.recentMoods.map(safeText).filter(Boolean).slice(-5) : [];
    data.questionAnswers = Math.max(0, Number(old.questionAnswers) || 0);
    data.learnedWords = Array.isArray(old.learnedWords) ? limitedWords(old.learnedWords.map(item => ({ id:safeText(item && item.id).slice(0,40), profileId:safeText(item && item.profileId).slice(0,30) || 'p-default', word:safeText(item && item.word).slice(0,12), category:['food','animal','play','thing','other'].includes(item && item.category) ? item.category : 'other', confidence:clamp(item && item.confidence || 1), taughtAt:safeTimestamp(item && item.taughtAt), lastUsedAt:safeTimestamp(item && item.lastUsedAt), usedCount:Math.max(0, Number(item && item.usedCount) || 0), correctedCount:Math.max(0, Number(item && item.correctedCount) || 0) })).filter(item => item.id && item.word && !privateLike(item.word) && !/(?:死にたい|自殺|けが|怪我|薬を|住所|電話|学校|メール|裸|性的|エッチ)/.test(item.word))) : [];
    const oldStory = old.bondStory && typeof old.bondStory === 'object' ? old.bondStory : {};
    data.bondStory = { chapter:safeText(oldStory.chapter).slice(0,20) || 'find', beat:safeText(oldStory.beat).slice(0,20) || 'idle', pendingWordId:safeText(oldStory.pendingWordId).slice(0,40), lastBeatAt:safeTimestamp(oldStory.lastBeatAt), unrelatedActions:Math.max(0, Math.min(2, Number(oldStory.unrelatedActions) || 0)), completedAt:safeTimestamp(oldStory.completedAt), recallReadyAt:safeTimestamp(oldStory.recallReadyAt), eventDates:oldStory.eventDates && typeof oldStory.eventDates === 'object' ? Object.fromEntries(Object.entries(oldStory.eventDates).map(([key,value]) => [safeText(key).slice(0,30), safeText(value).slice(0,12)]).filter(([,value]) => value)) : {}, preferenceShown:Boolean(oldStory.preferenceShown) };
    data.ownPreference = ['round','softSound','light','rain','warm'].includes(old.ownPreference) ? old.ownPreference : 'round';
    data.urge = ['curious','playful','quiet','sleepy','proud'].includes(old.urge) ? old.urge : 'curious'; data.attention = clamp(old.attention === undefined ? 50 : old.attention); data.surpriseSeed = Math.max(0, Math.floor(Number(old.surpriseSeed) || 17));
    data.moments = Array.isArray(old.moments) ? old.moments.map(item => ({ id:safeText(item && item.id).slice(0,50), profileId:safeText(item && item.profileId).slice(0,30) || 'p-default', type:'learned-word', word:safeText(item && item.word).slice(0,12), category:['food','animal','play','thing','other'].includes(item && item.category) ? item.category : 'other', text:safeText(item && item.text).slice(0,40), at:safeTimestamp(item && item.at) })).filter(item => item.id && item.word).slice(-30) : [];
    data.lastReplies = Array.isArray(old.lastReplies) ? old.lastReplies.slice(-12) : [];
    const TROUBLE_KINDS = ['puni','book','window','hiccup','leaf','ball'];
    const oldTrouble = old.trouble && typeof old.trouble === 'object' ? old.trouble : {};
    const oldTroubleDaily = oldTrouble.daily && typeof oldTrouble.daily === 'object' ? oldTrouble.daily : {};
    const troubleToday = today(now);
    const troubleSameDay = oldTroubleDaily.date === troubleToday;
    const troubleKinds = Array.isArray(oldTroubleDaily.kinds) ? [...new Set(oldTroubleDaily.kinds.map(value => safeText(value).slice(0, 10)).filter(value => TROUBLE_KINDS.includes(value)))].slice(0, 6) : [];
    const oldTroubleActive = oldTrouble.active && typeof oldTrouble.active === 'object' && TROUBLE_KINDS.includes(oldTrouble.active.kind) ? oldTrouble.active : null;
    data.trouble = {
      active: oldTroubleActive && oldTroubleActive.date === troubleToday ? { kind:oldTroubleActive.kind, petId:oldTroubleActive.petId === 'pet-2' ? 'pet-2' : 'pet-1', startedAt:safeTimestamp(oldTroubleActive.startedAt), hide:['left','right','bottom'].includes(oldTroubleActive.hide) ? oldTroubleActive.hide : '', date:troubleToday } : null,
      daily: { date:troubleToday, count:troubleSameDay ? Math.max(0, Math.min(99, Math.floor(Number(oldTroubleDaily.count) || 0))) : 0, kinds:troubleSameDay ? troubleKinds : [] },
      helpLog: Array.isArray(oldTrouble.helpLog) ? oldTrouble.helpLog.map(item => ({ date:safeText(item && item.date).slice(0, 10), kind:TROUBLE_KINDS.includes(item && item.kind) ? item.kind : '', petId:item && item.petId === 'pet-2' ? 'pet-2' : 'pet-1', at:safeTimestamp(item && item.at) })).filter(item => /^\d{4}-\d{2}-\d{2}$/.test(item.date) && item.kind).slice(-60) : [],
      helpTotal: Math.max(0, Math.floor(Number(oldTrouble.helpTotal) || 0)),
      enabled: oldTrouble.enabled !== false
    };
    data.ritual = normalizeRitual(old.ritual && typeof old.ritual === 'object' ? old.ritual : {}, now);
    const profileSafe = value => safeText(value).slice(0, 8);
    const hadProfiles = Array.isArray(old.profiles) && old.profiles.length > 0; const rawProfiles = hadProfiles ? old.profiles : [];
    data.profiles = rawProfiles.map((item, index) => ({ id:safeText(item && item.id).slice(0, 30) || `p-${index + 1}`, name:profileSafe(item && item.name) && !privateLike(profileSafe(item && item.name)) ? profileSafe(item.name) : `ひと${index + 1}`, childName:safeText(item && item.childName).slice(0,12), likes:listSafe(item && item.likes), dislikes:listSafe(item && item.dislikes), recentMoods:Array.isArray(item && item.recentMoods) ? item.recentMoods.map(safeText).filter(Boolean).slice(-7) : [], visitDates:Array.isArray(item && item.visitDates) ? item.visitDates.map(value => safeText(value).slice(0,10)).filter(Boolean).slice(-7) : [], createdAt:safeTimestamp(item && item.createdAt) || safeTimestamp(new Date(now).toISOString()), lastSeenAt:safeTimestamp(item && item.lastSeenAt), interactionCount:Math.max(0, Number(item && item.interactionCount) || 0), activePetId:item && item.activePetId === 'pet-2' ? 'pet-2' : 'pet-1',activePetTurnCount:Math.max(0,Math.min(4,Math.floor(Number(item && item.activePetTurnCount)||0))),switchAfterTurn:Math.max(2,Math.min(4,Math.floor(Number(item && item.switchAfterTurn)||2))) })).filter(item => item.id && item.name).slice(0, 5);
    if (!data.profiles.length) data.profiles = [{id:'p-default',name:'いつものひと',childName:data.childName,likes:data.likes.slice(),dislikes:data.dislikes.slice(),recentMoods:data.recentMoods.slice(),visitDates:[],createdAt:safeTimestamp(new Date(now).toISOString()),lastSeenAt:'',interactionCount:0,activePetId:'pet-1',activePetTurnCount:0,switchAfterTurn:2}];
    if (data.profiles.length && !data.profiles[0].childName && data.childName) data.profiles[0].childName = data.childName;
    data.activeProfileId = data.profiles.some(item => item.id === old.activeProfileId) ? old.activeProfileId : data.profiles[0].id;
    const activeProfile = data.profiles.find(item => item.id === data.activeProfileId) || data.profiles[0]; if (!hadProfiles) { activeProfile.childName = data.childName; activeProfile.likes = data.likes.slice(); activeProfile.dislikes = data.dislikes.slice(); activeProfile.recentMoods = data.recentMoods.slice(-7); } else { if (Object.prototype.hasOwnProperty.call(old, 'childName')) activeProfile.childName = data.childName; if (Object.prototype.hasOwnProperty.call(old, 'likes')) activeProfile.likes = data.likes.slice(); if (Object.prototype.hasOwnProperty.call(old, 'dislikes')) activeProfile.dislikes = data.dislikes.slice(); if (Object.prototype.hasOwnProperty.call(old, 'recentMoods')) activeProfile.recentMoods = data.recentMoods.slice(-7); data.childName = activeProfile.childName || ''; data.likes = listSafe(activeProfile.likes); data.dislikes = listSafe(activeProfile.dislikes); data.recentMoods = Array.isArray(activeProfile.recentMoods) ? activeProfile.recentMoods.slice(-5) : []; }
    const progress = old.weekProgress && typeof old.weekProgress === 'object' ? old.weekProgress : {};
    data.weekProgress = { visitDates:Array.isArray(progress.visitDates) ? progress.visitDates.map(value => safeText(value).slice(0, 10)).filter(Boolean).slice(-7) : [], dayIndex:Math.max(1, Math.min(7, Number(progress.dayIndex) || 1)), dailyBeat:['greeting','question','activity','callback','done'].includes(progress.dailyBeat) ? progress.dailyBeat : 'greeting', dayHistory:progress.dayHistory && typeof progress.dayHistory === 'object' ? progress.dayHistory : {}, lastCallbackAt:safeTimestamp(progress.lastCallbackAt), completedAt:safeTimestamp(progress.completedAt) };
    data.safetyPausedAt = safeTimestamp(old.safetyPausedAt);
    const memory = item => ({ id:safeText(item && item.id).slice(0, 50) || `fact-${Date.now()}-${Math.random().toString(36).slice(2,6)}`, profileId:safeText(item && item.profileId).slice(0,30) || data.activeProfileId, type:safeText(item && item.type).slice(0,16) || 'word', value:safeText(item && (item.value || item.word)).slice(0,12), source:safeText(item && item.source).slice(0,16) || 'conversation', date:safeText(item && item.date).slice(0,10) || today(now), lastUsedAt:safeTimestamp(item && item.lastUsedAt), usedCount:Math.max(0, Number(item && item.usedCount) || 0) });
    data.factMemories = (Array.isArray(old.factMemories) ? old.factMemories : []).map(memory).filter(item => item.value && !privateLike(item.value)).slice(-60);
    data.learnedWords.forEach(item => { if (!data.factMemories.some(memory => memory.value === item.word && memory.type === 'word' && memory.profileId === item.profileId)) data.factMemories.push(memory({id:`word-${item.id}`,profileId:item.profileId,type:'word',value:item.word,source:'learned-word',date:item.taughtAt})); });
    data.factMemories = data.factMemories.slice(-60);
    data.playMemories = Array.isArray(old.playMemories) ? old.playMemories.map(item => ({id:safeText(item && item.id).slice(0,50),profileId:safeText(item && item.profileId).slice(0,30) || data.activeProfileId,game:safeText(item && item.game).slice(0,20),date:safeText(item && item.date).slice(0,10) || today(now),score:Math.max(0,Number(item && item.score)||0),satisfaction:['low','good','high'].includes(item && item.satisfaction) ? item.satisfaction : 'good'})).filter(item => item.id && item.game).slice(-30) : [];
    data.socialMood = ['close','curious','shy','calm','proud'].includes(old.socialMood) ? old.socialMood : 'curious';
    data.routine = old.routine && typeof old.routine === 'object' ? {morning:old.routine.morning||{},day:old.routine.day||{},evening:old.routine.evening||{},night:old.routine.night||{}} : {morning:{},day:{},evening:{},night:{}};
    data.recentActionKinds = Array.isArray(old.recentActionKinds) ? old.recentActionKinds.map(safeText).filter(Boolean).slice(-8) : [];
    data.callbackQueue = Array.isArray(old.callbackQueue) ? old.callbackQueue.map(item => ({...memory(item), used:Boolean(item && item.used)})).filter(item => item.value && !item.used).slice(-12) : data.factMemories.slice(-12).map(item => ({...item,used:false}));
    normalizeV6Structures(data, old, now);
    normalizeActivePetIds(data);
    applyDeletionLedger(data);
    delete data.soundEnabled; data.version = 8; data.bondStage = Math.max(Number(old.bondStage) || 0, bondStage(data.bond));
    return data;
  }
  function bondStage(bond) { return clamp(bond) >= 70 ? 2 : clamp(bond) >= 30 ? 1 : 0; }
  function bondStageLabel(stage) { return ['はじめまして','なれてきた','ちいさな相棒'][Math.max(0, Math.min(2, Number(stage) || 0))]; }
  function traitLabel(traits, careCount) { const counts = careCount || {}; if (Object.values(counts).reduce((sum, value) => sum + (Number(value) || 0), 0) === 0) return 'まだわからない'; const values = traits || {}; const key = Object.keys({ playful:0, calm:0, talkative:0 }).sort((a,b) => (values[b] || 0) - (values[a] || 0))[0]; return { playful:'遊び好き', calm:'のんびり', talkative:'おしゃべり好き' }[key]; }
  function applyAction(data, action, now = new Date()) {
    const kind = action || 'tap'; data.careCount = data.careCount || {}; data.traits = data.traits || {};
    data.recentActionKinds = [...(Array.isArray(data.recentActionKinds) ? data.recentActionKinds : []), kind].slice(-8);
    data.socialMood = ({tap:'close',stroke:'calm',hold:'proud',play:'close',sleep:'calm',talk:'curious'}[kind] || 'curious');
    const hour = (now instanceof Date ? now : new Date(now)).getHours(); const routineKey = hour < 7 || hour >= 20 ? 'night' : hour < 12 ? 'morning' : hour < 17 ? 'day' : 'evening'; data.routine = data.routine || {morning:{},day:{},evening:{},night:{}}; data.routine[routineKey] = data.routine[routineKey] || {}; data.routine[routineKey][kind] = (Number(data.routine[routineKey][kind]) || 0) + 1;
    const profile = (data.profiles || []).find(item => item.id === data.activeProfileId); if (profile) { profile.interactionCount = Math.max(0, Number(profile.interactionCount) || 0) + 1; profile.lastSeenAt = new Date(now || Date.now()).toISOString().slice(0,30); }
    data.attention = clamp((Number(data.attention) || 50) + (kind === 'sleep' ? -15 : kind === 'talk' ? 4 : 8)); data.urge = ({ tap:'playful', stroke:'quiet', hold:'proud', play:'playful', sleep:'sleepy', talk:'curious' }[kind] || 'curious');
    data.careCount[kind] = (Number(data.careCount[kind]) || 0) + 1; data.daily = data.daily || { date:today(), talk:0, touch:0, play:0, seenReplyIds:[] };
    if (kind === 'talk') { data.daily.talk += 1; data.traits.talkative = clamp((data.traits.talkative || 50) + 2); data.bond = clamp(data.bond + 1); data.mood = clamp(data.mood + 1); }
    if (kind === 'tap') { data.daily.touch += 1; data.traits.playful = clamp((data.traits.playful || 50) + 1); data.bond = clamp(data.bond + 1); data.mood = clamp(data.mood + 2); data.curiosity = clamp(data.curiosity + 1); }
    if (kind === 'stroke' || kind === 'hold') { data.daily.touch += 1; data.traits.calm = clamp((data.traits.calm || 50) + (kind === 'hold' ? 2 : 1)); data.bond = clamp(data.bond + 2); data.mood = clamp(data.mood + 3); }
    if (kind === 'play') { data.daily.play += 1; data.traits.playful = clamp((data.traits.playful || 50) + 3); data.bond = clamp(data.bond + 2); data.mood = clamp(data.mood + 5); data.energy = clamp(data.energy - 3); data.curiosity = clamp(data.curiosity + 3); }
    if (kind === 'sleep') { data.traits.calm = clamp((data.traits.calm || 50) + 3); data.energy = clamp(data.energy + 12); data.mood = clamp(data.mood + 2); }
    data.bondStage = Math.max(Number(data.bondStage) || 0, bondStage(data.bond)); syncLegacyToActivePet(data); return data;
  }
  function applyGameResult(data, score, now = new Date()) { const points = Math.max(0, Math.min(8, Number(score) || 0)); applyAction(data, 'play', now); data.attention = clamp((Number(data.attention) || 50) + 8); data.urge = 'playful'; data.bond = clamp(data.bond + (points >= 5 ? 3 : points ? 2 : 1)); data.mood = clamp(data.mood + (points >= 8 ? 10 : points >= 5 ? 7 : 3)); data.energy = clamp(data.energy - (points >= 5 ? 3 : 1)); data.curiosity = clamp(data.curiosity + Math.min(5, points)); data.traits.playful = clamp((data.traits.playful || 50) + 1); data.bondStage = Math.max(Number(data.bondStage) || 0, bondStage(data.bond)); syncLegacyToActivePet(data); return data; }
  function classifyTouch({ durationMs = 0, deltaX = 0, deltaY = 0 } = {}) { if (Math.abs(deltaX) >= 60 && Math.abs(deltaX) > Math.abs(deltaY)) return 'stroke'; if (durationMs >= 650) return 'hold'; return 'tap'; }
  function isQuietTime(value) { const date = value instanceof Date ? value : new Date(value || Date.now()); const minutes = date.getHours() * 60 + date.getMinutes(); return minutes >= 20 * 60 + 30 || minutes < 7 * 60; }
  const PET_SLEEP_HOURS = { 'pet-1': { sleep: 22 * 60, wake: 8 * 60 }, 'pet-2': { sleep: 20 * 60 + 30, wake: 5 * 60 + 30 } };
  function isPetSleeping(petId, value) { const date = value instanceof Date ? value : new Date(value || Date.now()); const minutes = date.getHours() * 60 + date.getMinutes(); const config = PET_SLEEP_HOURS[petId]; if (!config) return false; if (config.sleep < config.wake) { return minutes >= config.sleep && minutes < config.wake; } else { return minutes >= config.sleep || minutes < config.wake; } }
  function echoDaily(data, now = new Date()) { if (!data) return null; const date = today(now); if (!data.daily || data.daily.date !== date) data.daily = { date, talk:0, touch:0, play:0, seenReplyIds:[], echoInviteCount:0, echoSessionCount:0, echoRoundCount:0, lastEchoInviteAt:'' }; data.daily.echoInviteCount = Math.max(0, Math.min(5, Math.floor(Number(data.daily.echoInviteCount) || 0))); data.daily.echoSessionCount = Math.max(0, Math.floor(Number(data.daily.echoSessionCount) || 0)); data.daily.echoRoundCount = Math.max(0, Math.floor(Number(data.daily.echoRoundCount) || 0)); data.daily.lastEchoInviteAt = safeTimestamp(data.daily.lastEchoInviteAt); return data.daily; }
  function canInviteEcho(data, { now = new Date(), visible = true, lastInteractionAt = 0, blocked = false, quickExitUntil = 0 } = {}) { const current = now instanceof Date ? now.getTime() : new Date(now).getTime(); if (!data || !Number.isFinite(current) || data.echoModeEnabled !== true || data.soundMode === 'text' || data.energy < 20 || !visible || blocked || isQuietTime(now) || isSafetyPaused(data, now)) return false; const daily = echoDaily(data, now); if (!daily || daily.echoInviteCount >= 5 || current < Number(quickExitUntil || 0) || current - new Date(lastInteractionAt || 0).getTime() < 45000) return false; const last = Date.parse(daily.lastEchoInviteAt || ''); return !Number.isFinite(last) || current - last >= 20 * 60 * 1000; }
  function recordEchoInvite(data, now = new Date()) { const daily = echoDaily(data, now); if (!daily || daily.echoInviteCount >= 5) return false; daily.echoInviteCount += 1; daily.lastEchoInviteAt = safeTimestamp(new Date(now).toISOString()); return true; }
  function recordEchoSession(data, now = new Date()) { const daily = echoDaily(data, now); if (!daily) return false; daily.echoSessionCount += 1; return true; }
  function recordEchoRound(data, now = new Date()) { const daily = echoDaily(data, now); if (!daily) return false; daily.echoRoundCount += 1; return true; }
  function echoShouldEnd(session, now = Date.now()) { if (!session) return 'ended'; const current = now instanceof Date ? now.getTime() : Number(now); if (!Number.isFinite(current)) return 'timeout'; const started = Number(session.startedAt); const startedAt = Number.isFinite(started) ? started : current; if (session.rounds >= session.targetRounds) return 'satisfied'; if (current - startedAt >= 120000) return 'timeout'; const lastAction = Number(session.lastActionAt); const lastVoice = Number(session.lastVoiceAt); const lastActivity = Math.max(Number.isFinite(lastAction) ? lastAction : startedAt, Number.isFinite(lastVoice) ? lastVoice : startedAt, startedAt); if (current - lastActivity >= 25000) return 'idle'; if (Number(session.consecutiveFailures || 0) >= 2) return 'failed'; return ''; }
  function canSpontaneousSpeak({ now = new Date(), lastInteractionAt = 0 } = {}) { const current = now instanceof Date ? now.getTime() : new Date(now).getTime(); return !isQuietTime(now) && current - new Date(lastInteractionAt || 0).getTime() >= 90000; }
  function decayAttention(data, elapsedMs = 0) { if (!data) return data; const hours = Math.max(0, Number(elapsedMs) || 0) / 3600000; data.attention = clamp((Number(data.attention) || 50) - Math.min(30, hours * 3)); if (hours >= 8) data.urge = 'sleepy'; return data; }
  function recordQuestion(data, themeId, answer, now = new Date(), details = {}) {
    if (!data) return data;
    const theme = safeText(themeId).slice(0, 20); const type = safeText(details.type || details.answeredQuestionType).slice(0, 12); const raw = safeText(details.rawValue || answer).slice(0, 20);
    data.themeDates = data.themeDates || {}; if (theme) data.themeDates[theme] = today(now);
    const profile = (data.profiles || []).find(item => item.id === data.activeProfileId); if (theme === 'mood' && type === 'mood' && raw) { data.recentMoods = Array.isArray(data.recentMoods) ? data.recentMoods.concat(raw).filter(Boolean).slice(-5) : [raw]; if (profile) profile.recentMoods = (Array.isArray(profile.recentMoods) ? profile.recentMoods : []).concat(raw).filter(Boolean).slice(-7); }
    if (theme === 'food' && type === 'word' && raw && !privateLike(raw) && !/死にたい|自殺|けが|怪我|薬|住所|電話|学校|メール|裸|性的|エッチ/.test(raw) && !/^(?:yes|no|うん|ううん|はい|いいえ)$/.test(raw)) data.likes = listSafe((Array.isArray(data.likes) ? data.likes : []).concat(raw));
    if (profile) { profile.likes = listSafe(data.likes); profile.dislikes = listSafe(data.dislikes); }
    data.questionAnswers = Math.max(0, Number(data.questionAnswers) || 0) + 1; return data;
  }
  function getWordStory(data, profileId = '') { if (!data) return null; const id = profileId || data.activeProfileId || 'p-default'; if (!data.wordMemoryV2 || typeof data.wordMemoryV2 !== 'object') data.wordMemoryV2 = {stories:[],requestDate:'',requestProfileId:'',deletionLedger:[]}; if (!Array.isArray(data.wordMemoryV2.stories)) data.wordMemoryV2.stories = []; let story = data.wordMemoryV2.stories.find(item => item && item.profileId === id); if (!story) { story = normalizeWordStory(id === (data.activeProfileId || 'p-default') ? data.bondStory : null,id); data.wordMemoryV2.stories.push(story); } if (id === (data.activeProfileId || 'p-default')) data.bondStory = story; return story; }
  function getProfilePetState(data, profileId = '', petId = 'pet-1') { const id = profileId || data && data.activeProfileId || 'p-default'; return data && Array.isArray(data.profilePetStates) ? data.profilePetStates.find(item => item.profileId === id && item.petId === petId) || null : null; }
  function getPairRelation(data, profileId = '') { const id = profileId || data && data.activeProfileId || 'p-default'; return data && Array.isArray(data.pairRelations) ? data.pairRelations.find(item => item.profileId === id) || null : null; }
  function getActivePetId(data, profileId = '') { const id = profileId || data && data.activeProfileId || 'p-default'; const profile = data && (data.profiles || []).find(item => item && item.id === id); const relation = getPairRelation(data, id); return profile && profile.activePetId === 'pet-2' && relation && ['visiting','cohabiting'].includes(relation.phase) ? 'pet-2' : 'pet-1'; }
  function setActivePetId(data, petId, profileId = '') { const id = profileId || data && data.activeProfileId || 'p-default'; const profile = data && (data.profiles || []).find(item => item && item.id === id); const relation = getPairRelation(data, id); if (!profile) return false; const next = petId === 'pet-2' && relation && ['visiting','cohabiting'].includes(relation.phase) ? 'pet-2' : 'pet-1'; const changed = profile.activePetId !== next; if (!changed) return false; if (id === data.activeProfileId) syncLegacyToActivePet(data); profile.activePetId = next; if (id === data.activeProfileId) syncLegacyFromActivePet(data); return true; }
  function advanceActivePetTurn(data, profileId = '', nextBoundary = 0) { const id = profileId || data && data.activeProfileId || 'p-default'; const profile = data && (data.profiles || []).find(item => item && item.id === id); const relation = getPairRelation(data, id); if (!profile || !relation || !['visiting','cohabiting'].includes(relation.phase)) return ''; profile.activePetTurnCount = Math.max(0, Number(profile.activePetTurnCount) || 0) + 1; const boundary = Math.max(2, Math.min(4, Math.floor(Number(nextBoundary) || Number(profile.switchAfterTurn) || 2))); profile.switchAfterTurn = boundary; if (profile.activePetTurnCount < boundary) return ''; profile.activePetTurnCount = 0; profile.switchAfterTurn = 2 + Math.floor(Math.random() * 3); return getActivePetId(data, id) === 'pet-1' ? 'pet-2' : 'pet-1'; }
  function getStageState(data, profileId = '', value) { const id = profileId || data && data.activeProfileId || 'p-default'; const at = value instanceof Date ? value : new Date(value || Date.now()); const relation = getPairRelation(data, id); const pairAvailable = Boolean(relation && ['visiting','cohabiting'].includes(relation.phase)) || (isPetSleeping('pet-1', at) && !isPetSleeping('pet-2', at)); const candidates = pairAvailable ? ['pet-1','pet-2'] : ['pet-1']; const awakePetIds = candidates.filter(petId => !isPetSleeping(petId, at)); const allAsleep = awakePetIds.length === 0; const stored = getActivePetId(data, id); const activePetId = allAsleep ? stored : (awakePetIds.includes(stored) ? stored : awakePetIds[0]); return { activePetId, awakePetIds, allAsleep, pairAvailable }; }
  function syncLegacyToActivePet(data) { const petState = getProfilePetState(data,'',getActivePetId(data)); if (!petState) return null; petState.bond=clamp(data.bond); petState.mood=clamp(data.mood); petState.energy=clamp(data.energy); petState.traits={playful:clamp(data.traits&&data.traits.playful),calm:clamp(data.traits&&data.traits.calm),talkative:clamp(data.traits&&data.traits.talkative)}; return petState; }
  function syncLegacyFromActivePet(data) { const petState = getProfilePetState(data,'',getActivePetId(data)); if (!petState) return null; data.bond=petState.bond; data.mood=petState.mood; data.energy=petState.energy; data.traits={...petState.traits}; data.bondStage=Math.max(Number(data.bondStage)||0,bondStage(data.bond)); return petState; }
  function purgeWordReferences(data, profileId, wordId) { if (!data || !profileId || !wordId) return false; const removed=(data.learnedWords||[]).filter(item=>(item.profileId||'p-default')===profileId&&item.id===wordId); const values=removed.map(item=>item.word); data.learnedWords=(data.learnedWords||[]).filter(item=>!((item.profileId||'p-default')===profileId&&item.id===wordId)); data.factMemories=(data.factMemories||[]).filter(item=>!(item.profileId===profileId&&(item.id===`word-${wordId}`||values.includes(item.value)))); data.callbackQueue=(data.callbackQueue||[]).filter(item=>!(item.profileId===profileId&&(item.id===`word-${wordId}`||values.includes(item.value)))); data.moments=(data.moments||[]).filter(item=>!((item.profileId||'p-default')===profileId&&(item.wordId===wordId||values.includes(item.word)))); if(data.weekProgress&&data.weekProgress.dayHistory&&typeof data.weekProgress.dayHistory==='object') Object.values(data.weekProgress.dayHistory).forEach(history=>{ if(history&&Array.isArray(history.callbackIds)) history.callbackIds=history.callbackIds.filter(id=>id!==wordId&&id!==`word-${wordId}`); }); const story=getWordStory(data,profileId); if(story&&story.pendingWordId===wordId){ const fresh=defaultWordStory(profileId); Object.keys(story).forEach(key=>delete story[key]); Object.assign(story,fresh); } (data.pairRelations||[]).filter(item=>item.profileId===profileId).forEach(relation=>{ relation.sharedWords=(relation.sharedWords||[]).filter(item=>item.wordId!==wordId); relation.sharedEvents=(relation.sharedEvents||[]).filter(item=>item.wordId!==wordId); }); return removed.length>0; }
  function purgeProfileReferences(data, profileId) { if(!data||!profileId)return false; data.factMemories=(data.factMemories||[]).filter(item=>item.profileId!==profileId); data.playMemories=(data.playMemories||[]).filter(item=>item.profileId!==profileId); data.callbackQueue=(data.callbackQueue||[]).filter(item=>item.profileId!==profileId); data.learnedWords=(data.learnedWords||[]).filter(item=>(item.profileId||'p-default')!==profileId); data.moments=(data.moments||[]).filter(item=>(item.profileId||'p-default')!==profileId); data.profilePetStates=(data.profilePetStates||[]).filter(item=>item.profileId!==profileId); data.pairRelations=(data.pairRelations||[]).filter(item=>item.profileId!==profileId); if(data.wordMemoryV2&&Array.isArray(data.wordMemoryV2.stories))data.wordMemoryV2.stories=data.wordMemoryV2.stories.filter(item=>item.profileId!==profileId); if(profileId!=='p-default'&&Array.isArray(data.profiles)&&data.profiles.length>1)data.profiles=data.profiles.filter(item=>item.id!==profileId); if(data.activeProfileId===profileId&&data.profiles&&data.profiles.length){ data.activeProfileId=data.profiles[0].id; const next=data.profiles[0]; data.childName=next.childName||'';data.likes=listSafe(next.likes);data.dislikes=listSafe(next.dislikes);data.recentMoods=Array.isArray(next.recentMoods)?next.recentMoods.slice(-7):[];getWordStory(data,next.id);syncLegacyFromActivePet(data); } return true; }
  function beginDeletion(data,{kind='word',profileId='',wordId='',now=new Date()}={}) { if(!data||!profileId||(kind==='word'&&!wordId))return null; if(!data.wordMemoryV2)data.wordMemoryV2={stories:[],requestDate:'',requestProfileId:'',deletionLedger:[]}; if(!Array.isArray(data.wordMemoryV2.deletionLedger))data.wordMemoryV2.deletionLedger=[]; const key=`${kind}:${profileId}:${wordId}`; let item=data.wordMemoryV2.deletionLedger.find(entry=>entry.id===key); if(!item){ item={id:key,kind:kind==='profile'?'profile':'word',profileId,wordId:kind==='profile'?'':wordId,createdAt:safeTimestamp(new Date(now).toISOString())}; data.wordMemoryV2.deletionLedger=[...data.wordMemoryV2.deletionLedger,item].slice(-40); } return item; }
  function completeDeletion(data,id){ if(!data||!data.wordMemoryV2||!Array.isArray(data.wordMemoryV2.deletionLedger))return false; const before=data.wordMemoryV2.deletionLedger.length; data.wordMemoryV2.deletionLedger=data.wordMemoryV2.deletionLedger.filter(item=>item.id!==id); return data.wordMemoryV2.deletionLedger.length<before; }
  function applyDeletionLedger(data){ if(!data||!data.wordMemoryV2||!Array.isArray(data.wordMemoryV2.deletionLedger))return data; data.wordMemoryV2.deletionLedger.forEach(item=>{ if(item.kind==='profile')purgeProfileReferences(data,item.profileId); else purgeWordReferences(data,item.profileId,item.wordId); }); return data; }
  function addProfile(data, name, now = new Date()) { const value = safeText(name).slice(0,8); if (!value || privateLike(value) || /死にたい|自殺|けが|怪我|薬|裸|性的|エッチ/.test(value) || (data.profiles || []).length >= 5) return null; const profile = {id:`p-${Date.now()}-${Math.random().toString(36).slice(2,5)}`,name:value,childName:'',likes:[],dislikes:[],recentMoods:[],visitDates:[],createdAt:safeTimestamp(now.toISOString()),lastSeenAt:'',interactionCount:0,activePetId:'pet-1',activePetTurnCount:0,switchAfterTurn:2}; data.profiles = [...(data.profiles || []), profile].slice(0,5); getWordStory(data,profile.id); data.profilePetStates=[...(data.profilePetStates||[]),defaultProfilePetState(profile.id,'pet-1'),defaultProfilePetState(profile.id,'pet-2')]; data.pairRelations=[...(data.pairRelations||[]),defaultPairRelation(profile.id)]; return profile; }
  function selectProfile(data, id) { if (!data || !(data.profiles || []).some(item => item.id === id)) return false; syncLegacyToActivePet(data); const current = (data.profiles || []).find(item => item.id === data.activeProfileId); if (current) { current.childName = safeText(data.childName).slice(0,12); current.likes = listSafe(data.likes); current.dislikes = listSafe(data.dislikes); current.recentMoods = Array.isArray(data.recentMoods) ? data.recentMoods.slice(-7) : []; } const next = data.profiles.find(item => item.id === id); data.activeProfileId = id; data.childName = next.childName || ''; data.likes = listSafe(next.likes); data.dislikes = listSafe(next.dislikes); data.recentMoods = Array.isArray(next.recentMoods) ? next.recentMoods.slice(-7) : []; getWordStory(data,id); syncLegacyFromActivePet(data); return true; }
  function deleteProfile(data, id) { if (!data || id === 'p-default' || (data.profiles || []).length <= 1) return false; purgeProfileReferences(data,id); data.profiles = data.profiles.filter(item => item.id !== id); if (data.activeProfileId === id) { data.activeProfileId = data.profiles[0].id; const next = data.profiles[0]; data.childName = next.childName || ''; data.likes = listSafe(next.likes); data.dislikes = listSafe(next.dislikes); data.recentMoods = Array.isArray(next.recentMoods) ? next.recentMoods.slice(-7) : []; getWordStory(data,next.id); syncLegacyFromActivePet(data); } return true; }
  function isSafetyPaused(data, now = new Date()) { const at = Date.parse(data && data.safetyPausedAt || ''); return Number.isFinite(at) && (now instanceof Date ? now.getTime() : new Date(now).getTime()) - at < 30000; }
  function pauseSafety(data, now = new Date()) { if (data) data.safetyPausedAt = new Date(now).toISOString(); return data; }
  return { createDefaultState, migrateState, bondStage, bondStageLabel, traitLabel, applyAction, applyGameResult, classifyTouch, isQuietTime, PET_SLEEP_HOURS, isPetSleeping, canSpontaneousSpeak, decayAttention, recordQuestion, privateLike, today, clamp, addProfile, selectProfile, deleteProfile, getWordStory, getProfilePetState, getPairRelation, getActivePetId, setActivePetId, advanceActivePetTurn, getStageState, syncLegacyToActivePet, syncLegacyFromActivePet, purgeWordReferences, purgeProfileReferences, beginDeletion, completeDeletion, applyDeletionLedger, isSafetyPaused, pauseSafety, echoDaily, canInviteEcho, recordEchoInvite, recordEchoSession, recordEchoRound, echoShouldEnd };
}));
